### ISSUE TITLE
`window` is undefined with NextJS (SSG and SSR)

### ISSUE THREAD

**Issue by GiovaniGuizzoBA** [secretkeylabs/sats-connect#104]
Importing `sats-connect` when using NextJS throws window is undefined due to server side rendering.

I suggest checking for `typeof window !== "undefined"` when using the window object to enable SSG and SSR compatibility. `@sats-connect/core` mainly works, but a few functions like `getProviders` fail if called outside useEffects.

**Comment by m-aboelenein** [comment]
Hey @GiovaniGuizzoYUB, thanks for reporting. We are aware of the issue and are currently trying to work on a fix 🙏

**Comment by Crescendo21** [comment]
Same issue here with next.js. I have window is undefined due to server side rendering. So when i wan't use :
const response = await Wallet.request('runes_mint', { ...

I have this kind of issue with the providers : 
Failed to select the provider. User may have cancelled the selection prompt." -32603

Is there a way to bypass this error ?

**Comment by GiovaniGuizzoBA** [comment]
I tried doing everything within a `useEffect`, however, it seems to fail when importing. I bypassed this by using `@sats-connect/core` instead.

**Comment by m-aboelenein** [comment]
@Crescendo21 @GiovaniGuizzoYUB can you try dynamically importing `sats-connect`?
```ts
  const handleMint = async () => {
    const { AddressPurpose, default: wallet } = await import("sats-connect");
    const response = await wallet.request("getAccounts", {
      purposes: [AddressPurpose.Ordinals, AddressPurpose.Payment],
    });
    console.log(response);
  };
```

**Comment by GiovaniGuizzoBA** [comment]
That could work, but now I already implemented everything using the core library. I created my own custom wallet select modal, and it seems to be working as expected.

**Comment by Crescendo21** [comment]
same issue :
---- my page.tsx
"use client"
import Wallet, { Address, BitcoinNetworkType } from 'sats-connect';
import  useLocalStorage  from "@/lib/useLocalStorage";
import MintRunes from "@/components/mint-rune";
import EtchRunes from "@/components/etch-rune";
import AddressDisplay from "@/components/address-display";
import NetworkSelector from "@/components/network-selector";

function App() {
  const [network, setNetwork] = useLocalStorage<BitcoinNetworkType>(
    'network',
    BitcoinNetworkType.Mainnet
  );
  const [addressInfo, setAddressInfo] = useLocalStorage<Address[]>('addresses', []);

  const isConnected = addressInfo.length > 0;

  const onConnect = async () => {
    const { AddressPurpose, default: wallet } = await import("sats-connect");
    const response = await wallet.request("getAccounts", {
      purposes: [AddressPurpose.Ordinals, AddressPurpose.Payment],
    });
    console.log(response);
  };

  const onDisconnect = () => {
    Wallet.disconnect();
    setAddressInfo([]);
  };

  if (!isConnected) {
    return (
      <div className="App">
        <header className="App-header">
          <img className="logo" src="/sats-connect.svg" alt="SatsConnect" />
          <NetworkSelector network={network} setNetwork={setNetwork} />
          <p>Click the button to connect your wallet</p>
          <button onClick={onConnect}>Connect</button>
        </header>
      </div>
    );
  }

  return (
    <div className="App">
      <div className="App-body">
        <div>
          <img className="logo" src="/sats-connect.svg" alt="SatsConnect" />
        </div>
        <AddressDisplay network={network} addresses={addressInfo} onDisconnect={onDisconnect} />

        <MintRunes network={network} addresses={addressInfo} />
        <EtchRunes network={network} addresses={addressInfo} />
      </div>
    </div>
  );
}

export default App;
---
-32603
"Failed to select the provider. User may have cancelled the selection prompt."

**Comment by Crescendo21** [comment]
same issue for me :
---
`"use client"
import Wallet, { Address, BitcoinNetworkType } from 'sats-connect';
import  useLocalStorage  from "@/lib/useLocalStorage";
import MintRunes from "@/components/mint-rune";
import EtchRunes from "@/components/etch-rune";
import AddressDisplay from "@/components/address-display";
import NetworkSelector from "@/components/network-selector";

function App() {
  const [network, setNetwork] = useLocalStorage<BitcoinNetworkType>(
    'network',
    BitcoinNetworkType.Mainnet
  );
  const [addressInfo, setAddressInfo] = useLocalStorage<Address[]>('addresses', []);

  const isConnected = addressInfo.length > 0;

  const onConnect = async () => {
    const { AddressPurpose, default: wallet } = await import("sats-connect");
    const response = await wallet.request("getAccounts", {
      purposes: [AddressPurpose.Ordinals, AddressPurpose.Payment],
    });
    console.log(response);
  };

  const onDisconnect = () => {
    Wallet.disconnect();
    setAddressInfo([]);
  };

  if (!isConnected) {
    return (
      <div className="App">
        <header className="App-header">
          <img className="logo" src="/sats-connect.svg" alt="SatsConnect" />
          <NetworkSelector network={network} setNetwork={setNetwork} />
          <p>Click the button to connect your wallet</p>
          <button onClick={onConnect}>Connect</button>
        </header>
      </div>
    );
  }

  return (
    <div className="App">
      <div className="App-body">
        <div>
          <img className="logo" src="/sats-connect.svg" alt="SatsConnect" />
        </div>
        <AddressDisplay network={network} addresses={addressInfo} onDisconnect={onDisconnect} />

        <MintRunes network={network} addresses={addressInfo} />
        <EtchRunes network={network} addresses={addressInfo} />
      </div>
    </div>
  );
}

export default App;`
---
-32603"Failed to select the provider. User may have cancelled the selection prompt."

**Comment by Crescendo21** [comment]
I get it. Connect is working dynamically

**Comment by fabienghr** [comment]
> That could work, but now I already implemented everything using the core library. I created my own custom wallet select modal, and it seems to be working as expected.

@GiovaniGuizzoYUB could you share the script here ? i'm stuck here and really don't know how to implement it

**Comment by stoXmod** [comment]
I faced the same issue. Don't use wallet connect inside hooks or stores (Zustand, Redux). Just create a component to handle the transactions and load dynamically in your parent component. The issue will be solved.

Here is a sample component.
```
import { useMemo, useState } from 'react';
import Wallet, {
  AddressPurpose,
  BitcoinNetworkType,
  Address
} from 'sats-connect';

type Props = {
  network: BitcoinNetworkType;
  addresses: Address[];
};

const EtchRunes = ({ addresses, network }: Props) => {
  const [totalCost, setTotalCost] = useState<number>();
  const [totalSize, setTotalSize] = useState<number>();
  const [fundTxId, setFundTxId] = useState<string>('');
  const [runeName, setRuneName] = useState<string>('');
  const [feeRate, setFeeRate] = useState<string>('');
  const [symbol, setSymbol] = useState<string>('');
  const [preMine, setPreMine] = useState<string>('');
  const [divisibility, setDivisibility] = useState<string>('');
  const [amount, setAmount] = useState<string>('');
  const [mintCap, setMintCap] = useState<string>('');

  const ordinalsAddress = useMemo(
    () =>
      addresses.find((a) => a.purpose === AddressPurpose.Ordinals)?.address ||
      '',
    [addresses],
  );

  const paymentAddress = useMemo(
    () =>
      addresses.find((a) => a.purpose === AddressPurpose.Payment)?.address ||
      '',
    [addresses],
  );

  const onClickEstimate = async () => {
    const response = await Wallet.request('runes_estimateEtch', {
      destinationAddress: ordinalsAddress,
      feeRate: +feeRate,
      symbol: symbol || undefined,
      premine: preMine || undefined,
      divisibility: +divisibility || undefined,
      terms:
        amount || mintCap
          ? {
              amount: amount || undefined,
              cap: mintCap || undefined,
            }
          : undefined,
      isMintable: true,
      runeName: runeName,
      network: network,
    });

    if (response.status === 'success') {
      setTotalCost(response.result.totalCost);
      setTotalSize(response.result.totalSize);
    } else {
      console.error(response.error);
      alert('Error Fetching Estimate. See console for details.');
    }
  };

  const onClickExecute = async () => {
    const response = await Wallet.request('runes_etch', {
      destinationAddress: ordinalsAddress,
      symbol: symbol || undefined,
      premine: preMine || undefined,
      terms:
        amount || mintCap
          ? {
              amount: amount || undefined,
              cap: mintCap || undefined,
            }
          : undefined,
      feeRate: +feeRate,
      isMintable: true,
      runeName,
      refundAddress: paymentAddress,
      network,
    });

    if (response.status === 'success') {
      setFundTxId(response.result.fundTransactionId);
    } else {
      console.error(response.error);
      alert('Error sending BTC. See console for details.');
    }
  };

  return (
    <>
    {/*  Place your UI */}
    </>
  );
};

export default EtchRunes;

````

Then import it into your parent component dynamically.

```
const EtchRunes = dynamic(() => import('@/components/EtchRunes'), {
  ssr: false,
});
```

**Comment by GiovaniGuizzoBA** [comment]
> > That could work, but now I already implemented everything using the core library. I created my own custom wallet select modal, and it seems to be working as expected.
> 
> @GiovaniGuizzoYUB could you share the script here ? i'm stuck here and really don't know how to implement it

I used something like this:

```typescript
import {
  AddressPurpose,
  DefaultAdaptersInfo,
  Provider,
  RpcErrorCode,
  defaultAdapters,
  getDefaultProvider,
  isProviderInstalled,
  removeDefaultProvider,
} from "@sats-connect/core";
import _ from "lodash";

function getConnectedWallet() {
  const providerId = getDefaultProvider();
  return _.find(DefaultAdaptersInfo, (value) => value.id === providerId);
}

const provider = getConnectedWallet();
if (provider && isProviderInstalled(provider.id)) {
  const providerAdapter = new defaultAdapters[provider.id]();
  const response = await providerAdapter.request("getAccounts", {
    purposes: [AddressPurpose.Ordinals, AddressPurpose.Payment, AddressPurpose.Stacks],
    message: "Gathering info.",
  });
}
```
If you set the default provider with `setDefaultProvider(provider.id);` (you can get the provider from `DefaultAdaptersInfo.xverse`), the code above will work. My modal selection simply sets the default provider and then calls the connection code.

**Comment by aryzing** [comment]
There's an [experimental version with Next.js support](https://github.com/secretkeylabs/sats-connect/pull/115),

```
npm i --save-exact sats-connect@2.2.2-f1061dc
```

let me know if it works.

**Comment by teebszet** [comment]
https://github.com/secretkeylabs/sats-connect/pull/115 resolved here
