### ISSUE TITLE
Issue with Rune Etching Not Reflecting on Explorers After Successful API Call

### ISSUE THREAD

**Issue by nawodyaishan** [secretkeylabs/sats-connect#105]
### Description
I am encountering an issue where a rune etching transaction was successfully submitted and confirmed on the blockchain, but the etched runes are not visible on any rune explorers. I used the `runes_etch` API method from the Sats Connect library.

### Environment
- **Network:** Testnet
- **Sats Connect Version:** 2.2.1

### API Payload - runes_estimateEtch
```json
{
    "destinationAddress": "tb1qzjhm26d90dga8dp3tgx07n76aky7psz4clagaz",
    "feeRate": 2,
    "runeName": "CCCCXCXCSXCZ",
    "divisibility": 8,
    "symbol": "C",
    "premine": "1000",
    "isMintable": true,
    "terms": {
        "amount": "1000",
        "cap": "1000"
    }
}
```

### Expected Behavior
The rune etching should be visible on the rune explorers such as Bitrune and RuneBTC after the transaction is confirmed on the blockchain.

### Actual Behavior
The transaction was confirmed as seen in the transaction on Mempool:  
[67e6cc2a7e4beaec8afccf28aba579b81a377550c5bdff635c04799087614e05](https://mempool.space/testnet/tx/67e6cc2a7e4beaec8afccf28aba579b81a377550c5bdff635c04799087614e05)  
However, the runes are not listed in the following rune explorers:  
- [Bitrune Explorer](https://explorer.bitrune.org/transactions)  
- [RuneBTC Testnet](https://testnet.runebtc.xyz/runes)

**Comment by emilcondrea** [comment]
Taking a look now

**Comment by emilcondrea** [comment]
Etching runes with custom name uses a commit & reveal scheme enforced by protocol. The reveal transaction is not yet confirmed and it uses very low fee rate. 

The order was submitted with fee rate of 2.

Testnet fees are crazy in last couple of days, please ensure you use correct fee rates so it gets confirmed.

This is the reveal transaction: https://mempool.space/testnet/tx/322c74678a49b0320b6d9f46b36aded6f11d8ba7c579f23e8841a94761ec95ac

**Comment by emilcondrea** [comment]
The transaction you linked, which is confirmed is the funding transaction which sends funds to the backend to etch the rune. Please also note that in order to be considered a valid rune, the reveal transaction should not be broadcasted earlier than 6 blocks after the commit transaction is confirmed.

**Comment by emilcondrea** [comment]
The fees used by funding transaction is good (67sat/vb), and you can choose it when signing the transaction. The fees used by subsequent commit & reveal transactions are controlled via feeRate parameter. You can check commit & reveal transaction by monitoring transactions made by the funding address on your behalf:

https://mempool.space/testnet/address/tb1p8lqryngkf8ejkcy0jnla75mvffgct7sz3y827jw8yn4lcfn6yk6sw9cksh

**Comment by emilcondrea** [comment]
Probably at the current testnet mempool of 600.000 pending transactions it will take a very long time for it to be confirmed at 2sat/vb. Please retry with a different feeRate.

**Comment by emilcondrea** [comment]
Please try with a different feeRate. We have multiple etches that were already etched via sats connect and all of them are visibile on public explorers.
