### ISSUE TITLE
How can I inscribe sat with this library?

### ISSUE THREAD

**Issue by ssoruf** [secretkeylabs/sats-connect#11]
Hello, can you provide some example to inscribe an html with sign transaction?

**Comment by victorkirov** [comment]
Hey @ssoruf 

Sorry for the extremely late reply.

I think at the time that you asked this, we didn't have the feature to inscribe from the wallet. It is now built in and you can see an example of it here: https://github.com/secretkeylabs/sats-connect-example/blob/main/src/components/createTextInscription.tsx

Please reopen the ticket if you need more help.
