### ISSUE TITLE
Automatic Distribution of Funds on Initial Mint

### ISSUE THREAD

**Issue by stoXmod** [secretkeylabs/sats-connect#110]
I am developing a runes platform and I have a specific functionality in mind regarding the distribution of funds during the minting process. 

Is there a way to automatically send 1% of the minting fees (or any specified amount) to a particular wallet each time a new item is minted? This feature would be crucial for automatically distributing royalties or similar payments.

#### Requirement
The goal is to ensure that every time an item is minted on our platform, a predetermined percentage of the transaction (in this case, 1%) is sent to a designated wallet address.

#### Questions
- Does the current API support this functionality?
- If not directly supported, what would be the recommended approach to implement such a feature?
- Are there any best practices or considerations we should keep in mind when attempting to implement this?

This feature is intended to streamline the process of royalties or fee distribution, making it more efficient and less prone to errors. Your advice on how to best achieve this would be greatly appreciated.

Thank you for your support and guidance!

**Comment by emilcondrea** [comment]
If I understand correctly you are interested to take a fee on each mint operation done on your platform. This is supported already, you can use appServiceFee & appServiceFeeAddress parameters. This will be added to the total amount that the user will pay, and will be sent automatically to fee address. https://docs.xverse.app/sats-connect/bitcoin-methods/mint-runes/runes_mint
