### ISSUE TITLE
Minting and etching a rune with your app incurs a fee of 2000 sats per rune

### ISSUE THREAD

**Issue by buildOrDie** [secretkeylabs/sats-connect#118]
### Description

It would be helpful to mention in your documentation that Minting with sat connect is not free and incurs fees, so that everyone is aware.

**Comment by teebszet** [comment]
hi @adaEggs , thanks for using sats connect!

indeed, the docs may have gone through many updates recently, but I can confirm, it is now listed at the bottom of these two pages: 
https://docs.xverse.app/sats-connect/bitcoin-methods/mint-runes/runes_mint
https://docs.xverse.app/sats-connect/bitcoin-methods/etch-runes/runes_etch

![image](https://github.com/secretkeylabs/sats-connect/assets/6109710/fe0e406b-f5b9-4462-b4ba-7df468c40db0)
