### ISSUE TITLE
[Unexpected token] - I can't run my react app with sats-connect 

### ISSUE THREAD

**Issue by taynguyen21** [secretkeylabs/sats-connect#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

2.3.0

### Current Behavior

in ./node_modules/@sats-connect/ui/dist/index.js

Module parse failed: Unexpected token (1202:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  

>    const a = Kr(o);
>      if (!a && t) {
>    ->  const l = new Error(i ?? Si(n, r));
>    throw l.name = "ContextError", (f = Error.captureStackTrace) == null || f.call(Error, l, s), l;
>     }

**Comment by teebszet** [comment]
hi @taynguyen21, do you have steps to reproduce, or link to a reproducible example?
