### ISSUE TITLE
How to get balance on Xverse wallet

### ISSUE THREAD

**Issue by 0xleopard** [secretkeylabs/sats-connect#12]
I tried to find getbalance on Xverse wallet, and unable to get the API yet.

Is there any documentation or demo available?

**Comment by yknl** [comment]
Once you have the address you can use any Bitcoin API to get the balance. For example: https://mempool.space/docs/api/rest

**Comment by thekoenekamp** [comment]
@yknl @victorkirov, I'm keen to know if there are plans to directly integrate a feature within Sats Connect for fetching user BTC & STX balances. Is this on your roadmap? Also, is mempool.space still the recommended option? Your insights on this would be greatly appreciated. Thank you sers!

FYI, I've noticed that all the Discord links in the documentation and on the website appear to be broken. Is there an active Discord community for Sats Connect (or Xverse) where one could join for more in-depth discussions and updates?

Additionally, I've spotted a small typo in the documentation on the page for "Selecting a provider with getProviderById" in [here](https://docs.xverse.app/sats-connect/wallet-provider/getproviders-and-getproviderbyid#selecting-a-provider-with-getproviderbyid):

It currently reads:
`const response = providerObject.reauest('getInfo', null);`

But it should be corrected to:
`const response = providerObject.request('getInfo', null);`

Hope this helps improve the documentation for everyone!

**Comment by victorkirov** [comment]
@thekoenekamp We are doing a revamp of sats-connect and it would be possible to add those as convenience methods. I'll let our product team know as it has been asked for before. Thanks also for the documentation note, we'll get that updated 👍 

For now, the easiest way is to use mempool.space. You can use the https://mempool.space/api/address/<address> endpoint and get the balance from the response.

For Discord, we closed all comms in the server as there were a lot of scammers around and we wanted to remove that form of access for them. We still have one channel open for developers but you have to be invited to join. Send me a DM @varak87 and I'll set you up.
