### ISSUE TITLE
["runes_etch" is not supported] Etch runes is not supported

### ISSUE THREAD

**Issue by LuisRivera1699** [secretkeylabs/sats-connect#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

2.3.x

### Current Behavior

I'm trying to integrate etch_runes API but this message is appearing me always when calling the function.

![image](https://github.com/secretkeylabs/sats-connect/assets/63574334/55b43d00-b24d-442d-9821-29c80cd6ef7a)

### Expected Behavior

It is supposed to create the order for etching rune.

**Comment by birchcode** [comment]
I've got a similar issue getting a 32601 error. Pasting from the [documentation](https://docs.xverse.app/sats-connect/wallet-providers/wallet.request#response-format-and-error-handling) it would imply the method isn't found:

```
enum RpcErrorCode {
  PARSE_ERROR = -32700, // Parse error	Invalid JSON
  INVALID_REQUEST = -32600, // The JSON sent is not a valid Request object.
  METHOD_NOT_FOUND = -32601, // The method does not exist/is not available.
  INVALID_PARAMS = -32602, // Invalid method parameter(s)
  INTERNAL_ERROR = -32603, // Internal JSON-RPC error
  USER_REJECTION = -32000, // user rejected/canceled the request
  METHOD_NOT_SUPPORTED = -32001, // method is not supported for the address provided
}
```

I also run into the same issue trying the runes_estimateMint method: `{code: -32601, message: '"runes_estimateMint" is not supported.'}`

I could be mistaken but I only see these methods once in the codebase.

**Comment by teebszet** [comment]
hi @LuisRivera1699 @birchcode , which version of the Xverse wallet is this integrating with?

---

update: runes_etch method is only supported in Xverse chrome extension >=0.32.0
