### ISSUE TITLE
MessageSign hash applied?

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#121]
### Description

Hi to everyone I would like to ask how can I get the hash of the message I am signing starting from the message I put inside the function, since it seems is not exactly the hash of the message itself

Is there any algo or encoding applied?

Thanks

**Comment by victorkirov** [comment]
Which address are you signing the message with? We use different hashes depending on the address since we use bip322 for the ordinals address and ECDSA signing for the payments address 👀

**Comment by victorkirov** [comment]
You can see the bip322 hash generation here: https://github.com/secretkeylabs/xverse-core/blob/develop/connect/bip322Signature.ts#L20
