### ISSUE TITLE
The transaction couldn’t proceed Request failed with status code 400

### ISSUE THREAD

**Issue by vendersen** [secretkeylabs/sats-connect#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

2.2.2

### Current Behavior

When I use the sats-connect api to build a sending transaction, the receiving address is TapRoot, and Xverse.app keeps prompting The transaction couldn’t proceed Request failed with status code 400,

### Expected Behavior

Transaction broadcast successful

### Steps To Reproduce

![1](https://github.com/secretkeylabs/sats-connect/assets/77932133/c0caf1b8-dcb5-476c-a79c-e9717e7b29e0)
![2](https://github.com/secretkeylabs/sats-connect/assets/77932133/609a643f-6f35-4d05-87c5-fd2213a72650)

**Comment by vendersen** [comment]
There is no problem with the Google Chrome plug-in wallet, I think it may be caused by the mobile wallet

**Comment by vendersen** [comment]
```
import {
	getProviders,
	getProviderById
} from 'sats-connect'

var Wallet = null
var walletAddr = null

export default {
	async Connect() {
		try {
			const providers = getProviders();

			const firstProvider = providers[0];

			Wallet = getProviderById(firstProvider.id);
			// 连接钱包
			const result = await Wallet.request('getAccounts', {
				purposes: ['payment','ordinals'],
				message: 'Address for receiving payments'
			});

			if (result.result) {
				if (result.result.length > 0) {
					walletAddr = result.result[0].address
					return walletAddr
				}
			}

			if (result.error) {
				throw new Error(result.error.message)
			}

		} catch (e) {
			//TODO handle the exception
			throw e
		}
	},
	GetAccount() {
		return walletAddr
	},
	async Send(recipient, amount) {
		try {
			// 发送比特币
			const result = await Wallet.request("sendTransfer", {
				recipients: [{
					address: recipient,
					amount: Number(amount),
				}]
			});
			if (result.result) {
				return result.result.txid
			}
			if (result.error) {
				throw new Error(result.error.message)
			}
			
		} catch (e) {
			throw e
		}

	}
}
```

**Comment by fedeerbes** [comment]
hi @vendersen, thanks for letting us know. i'll take a look and let you know as soon as i have an answer.

**Comment by fedeerbes** [comment]
hi @vendersen. i'm not able to reproduce this issue, i'm using mobile app version 1.30.1 and sats-connect 2.2.2. are you able to repro this issue consistently in latest mobile app version 1.30.1?
