### ISSUE TITLE
[bug] DAPP works on desktop but not on mobile xverse browser wallet

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

legacy

### Current Behavior

I am able to connect on desktop and sign txs at the following dapp but cant' work on mobile xverse app wallet

### Expected Behavior

It should work both on mobile and desktop

**Comment by elRaulito** [comment]
https://claimoor.vercel.app/

This is the dapp in mainnet

**Comment by fedeerbes** [comment]
Hi @elRaulito. thanks for reporting this. Can you share the version of the mobile app and what packages are used in the dapp? sats-connect or sats-connect/core and their versions.

**Comment by elRaulito** [comment]
App version: Android 1.30.1
Dapp uses "sats-connect": "1.4.1",

**Comment by elRaulito** [comment]
@fedeerbes

**Comment by fedeerbes** [comment]
@elRaulito thanks. i'll take a look and let you know as soon as i have an answer.

**Comment by fedeerbes** [comment]
Hi @elRaulito, we found the root of the issue, our docs for [signtransaction](https://docs.xverse.app/sats-connect-v1/methods/signtransaction) didn't reflect that `payload.message` is required and type `string`. Can you add that prop and let us know if this fixes the issue?

**Comment by elRaulito** [comment]
It works!
