### ISSUE TITLE
[Feature] Add support for silent account querying

### ISSUE THREAD

**Issue by 0xRAG** [secretkeylabs/sats-connect#139]
## Summary
As a dapp developer, I want to be able to query Xverse extension (and more generally, any wallet powered by sats-connect) for **connected** accounts, without any wallet prompt appearing in the case that the wallet is not currently connected to the dapp, or the wallet is locked.

Use case: enabling features like Dynamic's [multi-wallet](https://docs.dynamic.xyz/wallets/advanced-wallets/multi-wallet) with seamless UX, as seen on https://demo.dynamic.xyz/.

## Details
A function on sats-connect that, when called returns a `GetAddressResponse` with an empty `addresses` array if the wallet is locked, or if the wallet is not connected to the site, and importantly, does not prompt the user to unlock the wallet if it is locked, and does not prompt the user to connect to the site if the wallet is not already connected. If the wallet is unlocked and connected to the site, then this function should return the same value that `getAddress` would return.

### MetaMask
[`eth_accounts`](https://docs.metamask.io/wallet/reference/eth_accounts/) – returns empty array when MetaMask is locked or not connected to the site

### Phantom
[`onlyIfTrusted`](https://docs.phantom.app/solana/establishing-a-connection#eagerly-connecting) – throws an error when Phantom is not connected to the site, and will not open a popup until the `connect` method is called without `onlyIsTrusted: true`
> If this flag is present, Phantom will only eagerly connect and emit a connect event if the application is trusted. If the application is not trusted, Phantom will throw a [4001 error](https://docs.phantom.app/solana/errors) and remain disconnected until the user is prompted to connect without an onlyIfTrusted flag. In either case, Phantom will not open a pop-up window, making this convenient to use on all page loads.

**Comment by aryzing** [comment]
Thank you for opening the feature request. Supporting this behavior would require managing per-app perms on the wallet side. It's on our road-map, although can't provide an exact timeline.

**Comment by aryzing** [comment]
https://linear.app/xverseapp/issue/ENG-4515

**Comment by aryzing** [comment]
We now have support for per-app permissions allowing apps to query account data in the background after users have approved the connection request. For details, see the [sats-connect connection docs](https://docs.xverse.app/sats-connect/connecting-to-the-wallet/connect).
