### ISSUE TITLE
Request connection permissions and retrieve wallet data

### ISSUE THREAD

**Issue by abdolian** [secretkeylabs/sats-connect#142]
I've been working with the sats-connect package and tried running the example you provided [here](https://docs.xverse.app/sats-connect/connecting-to-the-wallet/request-connection-permissions-and-retrieve-wallet-data). Unfortunately, I encountered some issues, and it doesn't seem to work as expected. Could you please provide information about the latest version of your package and any updates or fixes that might address this problem?

**Comment by m-aboelenein** [comment]
> I've been working with the sats-connect package and tried running the example you provided [here](https://docs.xverse.app/sats-connect/connecting-to-the-wallet/request-connection-permissions-and-retrieve-wallet-data). Unfortunately, I encountered some issues, and it doesn't seem to work as expected. Could you please provide information about the latest version of your package and any updates or fixes that might address this problem?

Hi @abdolian,
This feature is still a work in progress, but we plan to release it soon. In the meantime, I'm happy to help with any other issues you might be experiencing with the latest version.

**Comment by teebszet** [comment]
@abdolian this was released in sats-connect 2.5.0 and supported by xverse chrome extension >=0.38.1, so that example in the docs should work with the latest versions.

thanks
