### ISSUE TITLE
[Feature] Runes transfer

### ISSUE THREAD

**Issue by kobimilan995** [secretkeylabs/sats-connect#147]
### Description

Hey folks, i see the runes_transfer method in the docs is coming soon. How soon will this be available? Are there any alternatives how i can do that?

**Comment by teebszet** [comment]
hi @kobimilan995 , runes_transfer will be coming _very_ soon. 

the alternative would be to construct the transaction yourself based on the protocol level guide: https://docs.ordinals.com/runes/specification.html#transferring

**Comment by ashneverdawn** [comment]
Any news on this? Is this still coming very soon? Thanks.

**Comment by DuskaT021** [comment]
> Any news on this? Is this still coming very soon? Thanks.

Hi @ashneverdawn runes_transfer is available via sats-connect if any further questions, head over to our discord server https://discord.gg/u6TCSngNXK and our support team will be able to help. Happy coding!
