### ISSUE TITLE
ord_createInscription is not working for small file sizes on Signet (50 KB)

### ISSUE THREAD

**Issue by denizhankara** [secretkeylabs/sats-connect#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

2.5.0

### Current Behavior

On Signet, ord_createInscription (https://docs.xverse.app/sats-connect/bitcoin-methods/createinscription) method is not working for inscribing Ordinals with around 50 KB file sizes (pokemon.png), saying:

<img width="459" alt="image" src="https://github.com/user-attachments/assets/a346cc62-7c79-4949-91ac-2d127e2e9cfc">

However, it works with 10 KB file sizes (pokemon2.png). Both sizes are small enough to create ordinals. Here is the component code I am using, added to https://github.com/secretkeylabs/sats-connect/tree/develop/example/src/components as a component:

`
import React, { useState, useEffect } from 'react';
import { createInscription } from 'sats-connect';
import { BitcoinNetworkType } from 'sats-connect';

import sampleImage from './pokemon.png'; // Import the sample image

type Props = {
  network: BitcoinNetworkType;
};

// Function to convert image file to base64
const toBase64 = (file: File) =>
  new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = (error) => reject(error);
  });

const CreateFileInscription = ({ network }: Props) => {
  const [content, setContent] = useState('');
  const [appFeeAddress, setAppFeeAddress] = useState('');
  const [appFee, setAppFee] = useState('');
  const [suggestedMinerFeeRate, setSuggestedMinerFeeRate] = useState('');
  const [txnId, setTxnId] = useState('');

  // Load and encode the sample image to base64 on component mount
  useEffect(() => {
    fetch(sampleImage)
      .then((res) => res.blob())
      .then((blob) => {
        const file = new File([blob], 'pokemon.png', { type: 'image/png' });
        return toBase64(file);
      })
      .then((base64) => {
        const base64Content = base64.split(',')[1]; // Remove the data:image/png;base64, prefix
        setContent(base64Content);
      })
      .catch(console.error);
  }, []);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      await createInscription({
        payload: {
          network: { type: network },
          contentType: 'image/png',
          content,
          payloadType: 'BASE_64',
          appFeeAddress,
          appFee: appFee ? parseInt(appFee, 10) : undefined,
          suggestedMinerFeeRate: suggestedMinerFeeRate
            ? parseInt(suggestedMinerFeeRate, 10)
            : undefined,
        },
        onFinish: (response) => {
          setTxnId(response.txId);
          alert(`Transaction ID: ${response.txId}`);
        },
        onCancel: () => alert('Canceled'),
      });
    } catch (error) {
      console.error('Error creating inscription:', error);
    }
  };

  return (
    <div className="card">
      <h3>Create File Inscription</h3>
      {!txnId && (
        <>
          <form onSubmit={handleSubmit}>
            <div>
              <div>Content (Base64 Encoded)</div>
              <input type="text" value={content} onChange={(e) => setContent(e.target.value)} />
            </div>
            <div>
              <div>App Fee Address (optional)</div>
              <input
                type="text"
                value={appFeeAddress}
                onChange={(e) => setAppFeeAddress(e.target.value)}
              />
            </div>
            <div>
              <div>App Fee (sats, optional)</div>
              <input type="number" value={appFee} onChange={(e) => setAppFee(e.target.value)} />
            </div>
            <div>
              <div>Suggested Miner Fee Rate (sats/byte, optional)</div>
              <input
                type="number"
                value={suggestedMinerFeeRate}
                onChange={(e) => setSuggestedMinerFeeRate(e.target.value)}
              />
            </div>
            <button type="submit" disabled={!content}>
              Create Inscription
            </button>
          </form>
        </>
      )}
      {txnId && (
        <div className="success">
          Success! Click{' '}
          <a
            href={`https://mempool.space/${
              network === BitcoinNetworkType.Mainnet ? '' : 'testnet/'
            }tx/${txnId}`}
            target="_blank"
            rel="noreferrer"
          >
            here
          </a>{' '}
          to see your transaction
        </div>
      )}
    </div>
  );
};

export default CreateFileInscription;

`

Here are the files I am trying to inscribe with:
![pokemon](https://github.com/user-attachments/assets/05cdb05a-cdb6-4f37-9339-24ccc88c0a07)
![pokemon2](https://github.com/user-attachments/assets/da352f65-a65c-4dab-a2f6-6c88fae20ea2)
[](url)is 

### Expected Behavior

The createInscription method should work with file sizes up to 100 KB at least.

### Steps To Reproduce

Steps To Reproduce
1- Checkout the most recent sats-connect lib, commit hash:
https://github.com/secretkeylabs/sats-connect/commit/f34ca7e7d210afc1f1d9e306ad3db6486e7bdb9e
https://github.com/secretkeylabs/sats-connect
2- Deploy example app on signet:
https://github.com/secretkeylabs/sats-connect/tree/develop/example
3- Try add the createInscription component with above code, and mint inscription on signet.

**Comment by denizhankara** [comment]
I found that the Signet file sizes are limited to smaller sizes than the mainnet. Is there a specific reason for this, and is it possible to allow the larger sizes on testnets?
<img width="384" alt="image" src="https://github.com/user-attachments/assets/f2e65277-951f-4d93-bab9-6f09d0a4e1f6">

**Comment by teebszet** [comment]
hi @denizhankara , the restrictions are in place for Signet and Testnet to keep those networks lighter in load.

for now it's unlikely to change, but let us know if this poses a significant problem for you
