### ISSUE TITLE
Ability to add collection name to ord_createInscription when inscribing from files

### ISSUE THREAD

**Issue by denizhankara** [secretkeylabs/sats-connect#153]
### Description

Hi, 

I am not sure if this is planned or implemented, however, it would be great if we are able to set collection names when using createInscription using files. Currently, the inscriptions created from files look like below (empty collection name)
<img width="544" alt="image" src="https://github.com/user-attachments/assets/9152fe6b-0ecf-4477-9e69-ac72d58f6753">

I use the method as per described:
await createInscription({
        payload: {
          network: { type: network },
          contentType: 'image/webp',
          content,
          payloadType: 'BASE_64',
          appFeeAddress,
          appFee: appFee ? parseInt(appFee, 10) : undefined,
        },
        onFinish: (response) => {
          setTxnId(response.txId);
          alert(`Transaction ID: ${response.txId}`);
        },
        onCancel: () => alert('Canceled'),
      });
    } catch (error) {
      console.error('Error creating inscription:', error);
    }
  };

**Comment by teebszet** [comment]
hi @denizhankara,

ordinal inscription collections can be defined by either:
- natively via parent-child inscriptions
- via marketplaces like Gamma, MagicEden indexing a group of inscriptions under a common collection

for the second option, you could feasibly inscribe your collection on chain first, and then submit the entire collection to be indexed on the marketplaces afterwards.

for the first option, while we don't support creating parent-child inscriptions in sats-connect yet, it could be included in the future if there is a demand for it. 

hope that helps!
