### ISSUE TITLE
[bug] Denying the connection request for `wallet_requestPermissions` does not return proper response with error

### ISSUE THREAD

**Issue by michalsmiarowski** [secretkeylabs/sats-connect#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

2.5.0, but it looks like it also happens on 2.6.0

### Current Behavior

When we call `wallet_requestPermissions` method with `Wallet.request()` it does not return proper response with error when we deny the connection request (like when we call `getAddresses` for example, which works properly).

Tested only for Xverse wallet.

### Expected Behavior

The `const res = await Wallet.request('wallet_requestPermissions', undefined);` should return a proper response when denying the connection request.

### Steps To Reproduce

1. Clone `sats-connect` repo
2. Install dependencies (`npm i`) in `sats-connect/example` and `sats-connect`
3. Build the project in `sats-connect` directory: `npm run build`
4. Run example app from `sats-connect` directory: `npm run dev:example`
5. Make sure you use fresh Xverse account without any permissions given
6. Click `Connect Account` button

<p align="center">
<img width="411" alt="image" src="https://github.com/user-attachments/assets/ad8a1603-1397-426d-a6f0-bd150d3fe4c6">
</p>

7. Click `Deny` when connection request modal appear

<p align="center">
<img width="355" alt="image" src="https://github.com/user-attachments/assets/199f8037-103b-483e-8d01-accbe6dc33b6">
</p>

After clicking the `Deny` button this error should appear in the console

https://github.com/secretkeylabs/sats-connect/blob/77f907385b9040b35401b3d81aeb80b22000835c/example/src/App.tsx#L51-L56

but nothing happens. Nothing is returned from this call so the code does not go further (although modal window is closed properly).

Similar code is also in [the docs](https://docs.xverse.app/sats-connect/connecting-to-the-wallet/request-connection-permissions-and-retrieve-wallet-data), and it has the same problem.

When we comment out the `wallet_requestPermissions` part and call `getAddresses` only, it properly returns response when we click `Cancel` and returns the error in the console. I believe the same should happen for `wallet_requestPermissions`. Again make sure to use fresh account that was not previously connected.

https://github.com/secretkeylabs/sats-connect/blob/77f907385b9040b35401b3d81aeb80b22000835c/example/src/App.tsx#L58-L66

<img width="593" alt="image" src="https://github.com/user-attachments/assets/0f6abe59-41bc-4839-a27b-b36e6db10be9">

### Anything else?

Based on my initial debugging, it appears that code execution stops here for `wallet_requestPermissions`, but it proceeds without issues for `getAddresses`

https://github.com/secretkeylabs/sats-connect/blob/77f907385b9040b35401b3d81aeb80b22000835c/src/index.ts#L87-L89

**Comment by aryzing** [comment]
Thanks for reporting, we'll take a look.

**Comment by aryzing** [comment]
We've identified the issue: an RPC message response being constructed in an unexpected format. Working on a fix now.

**Comment by teebszet** [comment]
this should be fixed as of Xverse chrome extension 0.39.1
