### ISSUE TITLE
[security] high severity axios vulnerability reported by npm

### ISSUE THREAD

**Issue by ashneverdawn** [secretkeylabs/sats-connect#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SATS-CONNECT Version

2.6.0

### Current Behavior

when running `npm install` it reports a high severity vulnerability
`npm audit` reveals some additional details:
<img width="648" alt="Screenshot 2024-08-14 at 1 21 10 PM" src="https://github.com/user-attachments/assets/9c9e65f0-64f6-47a0-9196-07acf25e610b">

Not sure about the implications of this vulnerability, but looks like updating to `axios 1.7.4` would solve it.

### Expected Behavior

no detected vulnerabilities by npm

### Steps To Reproduce

`npm install`
`npm audit`

**Comment by JanKortes212** [comment]
ok

**Comment by m-aboelenein** [comment]
Hey @ashneverdawn 

Thank you for bringing this issue to our attention. As part of our routine code maintenance, we have updated the `axios` version, and this change has been implemented in the latest release of sats-connect [v2.8.0](https://github.com/secretkeylabs/sats-connect/releases/tag/v2.8.0). Please note that, to the best of our knowledge, this issue did not introduce any security vulnerabilities.
