### ISSUE TITLE
How to use sats-connect to send btc?

### ISSUE THREAD

**Issue by liulise** [secretkeylabs/sats-connect#17]
Hello, how to use sats-connect to send btc,
There is no sendBtcTransaction method in the BitcoinProvider injected by Xverce wallet

**Comment by victorkirov** [comment]
Hi @liulise 

Apologies for the extremely late response.

If it helps, please see the example repo, specifically the send btc component here: https://github.com/secretkeylabs/sats-connect-example/blob/main/src/components/sendBitcoin.tsx

If you need further assistance, please reopen the issue.
