### ISSUE TITLE
Failed to sign transaction Error signing PSBT Error: Transaction is not finalized

### ISSUE THREAD

**Issue by topether21** [secretkeylabs/sats-connect#18]
Hi I am trying to sign this psbt.

Raw base64 PSBT:
`cHNidP8BAP1DAQIAAAAEC4oh5Bfz1UCdX8+RvDBodB5E/k3i8ae5Q7OHB0BsZFcAAAAAAP////8q0Vfy7QeKe612DANmR9NLOyZEYCpgQXOI864savGaVAAAAAAA//////eU9Mca42tI2RbL9LSePT95BBQHw7zSn83gPggS+DHjAAAAAAD9////KtFX8u0HinutdgwDZkfTSzsmRGAqYEFziPOuLGrxmlQDAAAAAP////8EoA8AAAAAAAAWABRG+puN8Rdm5ZniJvdzwp3/x9vNkhAnAAAAAAAAIlEghXRfbNOxsdp/3PoO+9kA1Bx2zgQMle4OAuL9jtf+76sQJwAAAAAAACJRINXhm8upw0QrrpC+6g3uLldgF37nrF1BlhGOZXu7MCFBBH4AAAAAAAAXqRSOFV167CO6HneNXI8b1TuBweJV9YcAAAAAAAEBH9AHAAAAAAAAFgAUpO6TPSrWG/GaJmF7Q5qaArJXrdQBAwQBAAAAAAEBH9AHAAAAAAAAFgAUVqiGgXC/LtZcdD1dcA1FiEhJTeEBAwQBAAAAAAEAsgIAAAACbG47gFYsNEQcqiDH11xz+B7Au07SN9rVZwiL4AP0xj8AAAAAAP3///8PCnnkz+O+Ly3Fb7GypSpVBBSLJeZFjrTKMWHFAus5FAEAAAAA/////wIQJwAAAAAAACJRINXhm8upw0QrrpC+6g3uLldgF37nrF1BlhGOZXu7MCFBqBYfAgAAAAAiUSCMa++bywFYHxziQdX4iNdm8QSMpT1yGRCIATs/X3GWUwAAAAABASsQJwAAAAAAACJRINXhm8upw0QrrpC+6g3uLldgF37nrF1BlhGOZXu7MCFBAQMEgwAAAAEIQwFBnBPixDdU9/0ybWM56CEQmgtzAwHcVw8E0hDLm9dB55XxLYO3OrxE1QYOYWvCi1Nt//+58f06XPh9QTezMIkMuoMAAQD9WgECAAAABKmjk2jSqQSdFQmlO3ENB+1rpA4m5fAeIcjMLX6KP8glAQAAAAD/////qaOTaNKpBJ0VCaU7cQ0H7WukDibl8B4hyMwtfoo/yCUAAAAAAP////86J+7W4aeuyrF3FftUGxDcJKd4cJWsmAYHp37JsnsAAAAAAAAA/f///9NAMgY0jKE7C6o3gAP0aVaeeZaVzCoWu1m+K+53K14QAQAAABcWABSocg1wHbw3K0prtPAJ26thGWTTa/////8E0AcAAAAAAAAWABRWqIaBcL8u1lx0PV1wDUWISElN4RAnAAAAAAAAIlEghXRfbNOxsdp/3PoO+9kA1Bx2zgQMle4OAuL9jtf+76sQJwAAAAAAACJRIJT2U14DpfCaVeihkdwRhKr66qzIfaSOAm2ka+Ulb+VsbOUAAAAAAAAXqRSOFV167CO6HneNXI8b1TuBweJV9YcAAAAAAQQWABSocg1wHbw3K0prtPAJ26thGWTTawAAAAAA`

My signing function

```ts
signByXverse: async (psbt, address) => {
  let psbtBase64 = '';
  const signPsbtOptions = {
      payload: {
          network: {
              type: 'Mainnet',
          } as BitcoinNetwork,
          message: 'Sign Transaction',
          psbtBase64: psbt,
          broadcast: false,
          inputsToSign: [
              {
                  address, // paymentAddress
                  signingIndexes: [3],
                  sigHash: bitcoin.Transaction.SIGHASH_ALL,
              },
          ],
      },
      onFinish: ({ psbtBase64: _psbtBase64, txId: _txId }) => {
          psbtBase64 = _psbtBase64;
      },
      onCancel: () => alert('Request canceled.'),
  };
  await signTransaction(signPsbtOptions);
  debugger;
  const finalPsbt = bitcoin.Psbt.fromBase64(psbtBase64, {
      network: NETWORK,
  }).finalizeInput(3);
  return finalPsbt;
},
```

<img width="359" alt="image" src="https://github.com/secretkeylabs/sats-connect/assets/126987350/6c1b5789-e354-4201-b830-cdf4a0226312">

**Comment by victorkirov** [comment]
Hi @topether21 

Huge apologies for the late response. This looks like it may have been a bug in the old code base which has subsequently been fixed. This should not happen if the broadcast flag is set to false.

Please reach out if there are any other issues, we are monitoring these issues more actively and will reply sooner. I'm going to close this one as it is most likely outdated.
