### ISSUE TITLE
Trouble verfiying signature

### ISSUE THREAD

**Issue by MuneerFergiani** [secretkeylabs/sats-connect#19]
When signing a message i get a signature that is 65 byte long what is up with that and what is the format of the public key, im having trouble verfiying the signature with bitcoinjs-lib because it doesn't accept the signature.

**Comment by yknl** [comment]
As far as I know, bitcoinjs-lib cannot verify BIP332 messages https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki

**Comment by jakehobbs** [comment]
@MuneerFergiani I found this library which seems to work perfectly out of the box to verify the signature: https://github.com/ACken2/bip322-js
