### ISSUE TITLE
Error in sendBtcTransaction 

### ISSUE THREAD

**Issue by Demiduska** [secretkeylabs/sats-connect#21]
[Connect] Error during send btc request TypeError: provider.sendBtcTransaction is not a function

**Comment by KennethAshley** [comment]
anything?

**Comment by Demiduska** [comment]
I wrote my own function for creating tx with iscure/btc-signer and then signing it with sats-connect

**Comment by KennethAshley** [comment]
@Demiduska mind sharing an example or sample code on how you did this?

**Comment by Demiduska** [comment]
`
const getUnspent = async (wallet: string) => {
    const response = await axios.get(
      `https://mempool.space/api/address/${wallet}/utxo`
    );
    return response.data;
  };


  const onClickMintXverseButton = async () => {
  
    const NETWORK = {
      bech32: "bc",
      pubKeyHash: 0x00,
      scriptHash: 0x05,
      wif: 0x80,
    };

    try {
      if (address && publicKey) {
        
        const utxos = await getUnspent(address);

        let inputs = [];
        let inputCount = 1;
        let outputCount = 1;

        const output = utxos[0];

        const xversePublicKey = hex.decode(publicKey);
        const tx = new btc.Transaction();

        const p2wpkh2 = btc.p2wpkh(xversePublicKey, NETWORK);
        const p2sh = btc.p2sh(p2wpkh2, NETWORK);

        const transactionSize =
          inputCount * 146 + outputCount * 34 + 10 - inputCount;

        let feeRate = 6;
        const responseFees = await axios.get(
          "https://mempool.space/api/v1/fees/recommended"
        );
        if (responseFees?.data) {
          feeRate = responseFees.data.halfHourFee;
        }

        const fee = transactionSize * feeRate;

        if (BigInt(output.value) - BigInt(fee) - BigInt(mintPrice) < 0) {
          setErrorTx("Balance is too low for this transaction");
          throw new Error("Balance is too low for this transaction");
        }

        tx.addInput({
          txid: output.txid,
          index: output.vout,
          witnessUtxo: {
            script: p2sh.script ? p2sh.script : Buffer.alloc(0),
            amount: BigInt(output.value),
          },
          redeemScript: p2sh.redeemScript ? p2sh.redeemScript : Buffer.alloc(0),
          witnessScript: p2sh.witnessScript,
          sighashType:
            btc.SignatureHash.SINGLE | btc.SignatureHash.ANYONECANPAY,
        });

        const walletFund =
          process.env.NEXT_PUBLIC_WALLET_FUND ?? "fallback-value";

        tx.addOutputAddress(walletFund, BigInt(mintPrice), NETWORK);
        tx.addOutputAddress(
          address,
          BigInt(output.value - fee - mintPrice),
          NETWORK
        );

        const psbt = tx.toPSBT(0);
        const psbtB64 = base64.encode(psbt);

        const signPsbtOptions = {
          payload: {
            network: {
              type: "Mainnet" as const,
            },
            message: "Sign Transaction",
            psbtBase64: psbtB64,
            broadcast: true,
            inputsToSign: [
              {
                address: address,
                signingIndexes: [0],
                sigHash:
                  btc.SignatureHash.SINGLE | btc.SignatureHash.ANYONECANPAY,
              },
            ],
          },
          onFinish: async (response: any) => {
            console.log(response);

            if (address && addressOrdinal) {
              const order = await createOrdinalOrder({
                txPaymentId: response.txId,
                wallet: address,
                walletOrdinal: addressOrdinal,
              });
              setOrder(order);
            }
          },
          onCancel: () => alert("Canceled"),
        };
        await signTransaction(signPsbtOptions);
      }
    } catch (e) {
      console.log(e);
    }
  };`
  
  Need to add a function for calculating all outputs, not only the first.

**Comment by KennethAshley** [comment]
@Demiduska thanks a bunch for this! quite a lot of code but I cant get `sendBtcTransaction` to work.

**Comment by victorkirov** [comment]
@KennethAshley this issue is a bit old now, apologies for the late response.

You shouldn't interact with the provider directly. You need to install sats-connect as a dependency and interact with the provider via the library. 

Please reopen the issue if you need assistance. I'll keep an eye on the issues in this repo more actively.
