### ISSUE TITLE
Unable to pass allowUnknowOutput to wallet to sign PSBT

### ISSUE THREAD

**Issue by mijoco-btc** [secretkeylabs/sats-connect#33]
Hi,

Creating a PSBT using outputs from a [transaction](https://mempool.space/testnet/tx/8dc16064c32592977cd8b2e077aaa9ae68ef8739152e905354f895b0ff9ac31f) with unknown output causes error;

> Error signing PSBT Error: Transaction/output: unknown output script type, there is a chance that input is unspendable. Pass allowUnkownScript=true, if you sure

I can't see a way to pass { allowUnknowInput: true, allowUnknowOutput: true } to the wallet to get it to ignore the unknown input/outputs because

```
transaction.toPSBT()
```

scure btc signer does not preserve these options on the PSBT and `SignTransactionOptions` has no options for ignoring unknown outputs?

**Comment by RenataDellamatriz** [comment]
Any updates? I have the same problem.

**Comment by victorkirov** [comment]
Apologies for the extremely late response. This was an issue in the scure signer library which has subsequently been updated. The issue should no longer persist as we updated the package as soon as the fix was made available. Please reopen this ticket if you are still having issues.
