### ISSUE TITLE
 In the Xverse APP wallet and call the sendBtcTransaction function, I cannot receive any callback.

### ISSUE THREAD

**Issue by whenhi** [secretkeylabs/sats-connect#37]
When I access my webpage through the browser in the Xverse APP wallet and call the sendBtcTransaction function, I cannot receive any callback.
However, it can be used normally when calling signMessage and getAddress.
When accessing the same web page on a browser with the Xverse browser extension installed, all three functions work fine.
I observed that Unisat's inscription mint page can be used normally in Xverse APP. This is the URL: https://unisat.io/inscribe
Is it the way I'm using it that's wrong? Can anyone help me, thank you!

**Comment by ely-alamillo** [comment]
@abdulhaseeb4239 I am having the same issue, any update on thi s?

**Comment by abdulhaseeb4239** [comment]
> @abdulhaseeb4239 I am having the same issue, any update on thi s?

We've identified the issue and have scheduled it to be addressed in our upcoming mobile release.

**Comment by ely-alamillo** [comment]
> > @abdulhaseeb4239 I am having the same issue, any update on thi s?
> 
> We've identified the issue and have scheduled it to be addressed in our upcoming mobile release.

Awsome, ty!
