### ISSUE TITLE
Public key format in getAddress function

### ISSUE THREAD

**Issue by pdyraga** [secretkeylabs/sats-connect#48]
This is how I retrieve the account's public key from Xverse:

```
const getAddressOptions = {
  payload: {
    purposes: ['ordinals'],
    message: 'Address for receiving Ordinals',
      network: {
        type:'Testnet'
      },
    },
    onFinish: (response) => {
      walletAddress = response.addresses[0].address
      walletPublicKey = response.addresses[0].publicKey
    },
    onCancel: () => alert('Request canceled'),
  }
}    

await getAddress(getAddressOptions);
```

The `walletPublicKey` returned has the following format: `12f022914336dea00c12940dcae0481fbf87484f09f88f6d0ac1b552997faa25`.

This looks to me like a compressed public key format but without the `02/03` prefix indicating the position of the Y point on the curve. Is my assumption of the key format correct and if so, is there a way to have the prefix included?

**Comment by victorkirov** [comment]
Hi @pdyraga and apologies for the late response

The ordinals address is a taproot address, so we return the Schnorr pub key for the address. This is derived using bip32 and the first byte is dropped, as per bip340.

Hope this helps. If you need more info, please reopen the ticket.
