### ISSUE TITLE
Finding inscriptions with sats-connect

### ISSUE THREAD

**Issue by bitdazzle** [secretkeylabs/sats-connect#49]
Hello,
I see in the X-verse wallet it can render all NFTs. I want to do the same in my app, I need to find all the inscriptions in the wallet with their collection names to do further processing. Can I do this using sats-connect?

Thanks!

**Comment by yknl** [comment]
This is not functionality that sats connect provides currently. I would suggest finding an API where you can get inscription per address data from.

**Comment by bitdazzle** [comment]
Thanks, so X-Verse is keeping this functionality local and not opening it for developer's usage, at least for now.

I thought if I could avoid multiple lookups, anyhow. Anyone interested in knowing the inscriptions in your X-verse wallet can use ordinals API by running your node or use the rest endpoint from https://docs.hiro.so/ordinals/specific-inscription.

**Comment by yknl** [comment]
The functionality is out of scope for Sats Connect. It's much better to directly hit the APIs for inscriptions instead of through Sats Connect.
