### ISSUE TITLE
Feature Request: Implement Listeners for Account and Network Changes and Non-Intrusive Account Retrieval

### ISSUE THREAD

**Issue by 0xboga** [secretkeylabs/sats-connect#54]
**Issue/Question:**

Hello Sats Connect Team,

I'm currently integrating Sats Connect into my application to connect with Xverse wallets. First off, I want to express my appreciation for your work on this library—it's been instrumental in simplifying the interaction between our app and Bitcoin wallets.

As I'm delving deeper into the development process, I've identified a few potential enhancements that could significantly benefit the user experience and overall functionality of the library:

1. **Listeners for Account and Network Changes**: Is there a possibility to implement listeners that can detect and respond to changes in the user's account or the network? This feature would be incredibly useful for dynamically updating the application state in response to such changes.

2. **Non-Intrusive Account Retrieval**: Currently, retrieving a user's account involves a wallet pop-up where the user needs to confirm the action. While this is secure, it can sometimes be intrusive, especially for users who frequently interact with the application. Is there a way to streamline this process? Specifically, I'm interested in an option to get the account details without prompting the user with a wallet pop-up each time, assuming they've already granted permission.

These enhancements, if feasible, could greatly improve the user experience by providing more seamless interactions and reducing repetitive confirmation steps.

I understand that these features might require careful consideration, especially concerning security and privacy. I'm eager to hear your thoughts on whether these enhancements align with the vision and roadmap for Sats Connect.

Additionally, I'd like to highlight that this request is related to the implementation discussed in [Issue #703 on the Xverse Web Extension repository](https://github.com/secretkeylabs/xverse-web-extension/issues/703). The successful integration of these features there would play a significant role in the effectiveness of the enhancements proposed here.

Thank you for your time and consideration. Looking forward to your insights.

Best regards.

**Comment by victorkirov** [comment]
@0xboga Thanks for this detailed write up and input. We're in the process of revamping sats connect, so this feedback is excellent. I'll forward it to our product team to see if we can and how we could implement these.

**Comment by 0xboga** [comment]
I noticed the recent update to the Sats Connect library and saw that event listeners for account changes are now included in the documentation: [Wallet Events Documentation](https://docs.xverse.app/sats-connect/wallet-events). This is exactly what I was hoping for, so I think this issue can be closed.

Thanks for implementing this feature and for the continuous improvements!
