### ISSUE TITLE
Is it compatible with iframes?

### ISSUE THREAD

**Issue by chejun3** [secretkeylabs/sats-connect#56]
On the Xverse app's browser for iPhone, it seems that getAddress cannot be called from an iframe. However, using the exact same code, I am able to call getAddress from a PC. Version 1.3.0.

**Comment by victorkirov** [comment]
Hi

I think we only inject the provider on the parents site on mobile. On desktop, Chrome injects the provider into every site automatically.

What is the use case for accessing it via iFrame?
