### ISSUE TITLE
Sending inscription

### ISSUE THREAD

**Issue by Spreeyka** [secretkeylabs/sats-connect#57]
Is there any API for sending inscription?

Equivalent of this from Unisat wallet: https://docs.unisat.io/dev/unisat-developer-service/unisat-wallet#sendinscription

**Comment by victorkirov** [comment]
This feature is not currently available, but should be in the next couple of weeks.

**Comment by victorkirov** [comment]
The ETA on this was a bit off 😅 It's currently being actively worked on, so expect it soon.

**Comment by teebszet** [comment]
this was released for sats-connect v2.6.0 and now supported from Xverse extension v0.39.0

https://docs.xverse.app/sats-connect/bitcoin-methods/ord_sendinscriptions
