### ISSUE TITLE
onCancel should return error

### ISSUE THREAD

**Issue by revofusion** [secretkeylabs/sats-connect#64]
Currently onCancel is very opaque and doesnt return the error that caused the cancel

**Comment by victorkirov** [comment]
This is indeed something that needs improvement. There is a new version of sats connect coming soon which will address this. Keep an eye out over the next week or 2.

**Comment by teebszet** [comment]
hi @revofusion, has this issue been resolved in the latest version of sats-connect?

thanks! 🙏
