### ISSUE TITLE
Keep getting this error when I try to create PSBTs with multisigs ps2h

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#70]
Transaction/sign: legacy input without nonWitnessUtxo, can result in attack that forces paying higher fees. Pass allowLegacyWitnessUtxo=true, if you sure

**Comment by victorkirov** [comment]
@elRaulito you'll have to specify the nonWitnessUtxo field for the input you want signed. This can be done by getting the UTXO's parent tx hex (from `https://mempool.space/api/tx/<txid>/hex`), converting the hex into a JS Buffer, and using that buffer as the nonWitnessUtxo value.

If you need some more help, it would be great if you could post some example code of what you're doing.

**Comment by elRaulito** [comment]
Thanks a lot, it worked!

I can use as nonWitnessUtxo even one in the mempool, not yet confirmed right? 

Can close the issue

**Comment by victorkirov** [comment]
Yup, it just needs to point to the previous txn. Thanks for confirming. Will close this issue.
