### ISSUE TITLE
Different Wallet Providers

### ISSUE THREAD

**Issue by skyrover7** [secretkeylabs/sats-connect#72]
Given that a number of other wallets in the space are using the sats-connect standard, is there a best practice or any documentation around getting wallet providers and allowing the user to choose which they'd like to use?

I've seen some folks in discord talk about ME wallet taking precedence over xverse, and I have also seen the sample ME wallet implementations, but nothing seems standardised. Any guidance appreciated!

**Comment by victorkirov** [comment]
Sats-connect will prioritise Xverse if the user has it installed and a specific provider has not been chosen. If you want to force a specific provider, you need to pass in a getProvider function with the payload for each request, which returns the provider you want to target.

e.g. for the getAddress function, you would do the below to force select Xverse:
```javascript
getAddress({
  getProvider: () => window.XverseProviders.BitcoinProvider,  // << this line
  payload: {
    purposes: [AddressPurpose.Ordinals, AddressPurpose.Payment, AddressPurpose.Stacks],
        ...
    },
    onFinish: (response) => {
      ...
  },
  onCancel: () => alert("Request canceled"),
});
```

**Comment by skyrover7** [comment]
thanks @victorkirov! is there a way to detect which providers are installed/available?

**Comment by victorkirov** [comment]
You can check for the providers of the specific wallets on the window object. For Xverse, you can do:
`const xverseInstalled = !!window.XverseProviders`

Note though that the providers aren't necessarily available on load so you might want to delay this check by a few seconds after the page loads.

There is no way to detect all wallets that implement the sats-connect standard though, so it's more of a verification that specific wallets are installed rather than an introspection of which wallets are available.

**Comment by skyrover7** [comment]
Thanks @victorkirov, that does seem to work for xverse, but not getting the equivalent for ME. Their sample code is below which seems pretty vague regarding the provider. Also i know there was an issue in discord about this

https://discord.com/channels/895889501560377364/1037095647335161868/1204727325095370772
![image](https://github.com/secretkeylabs/sats-connect/assets/42014195/550c6822-7a72-44fd-a44e-ae4b0f3242dc)

```jsx
async function connectWallet() {
  try {
    await getAddress({
      getProvider: async () =>
      (wallet as unknown as WalletWithFeatures<SatsConnectFeature>).features[SatsConnectNamespace]
      ?.provider,
      payload: {
        purposes: [AddressPurpose.Ordinals, AddressPurpose.Payment],
        message: 'Address for receiving Ordinals and payments',
        network: {
          type: BitcoinNetworkType.Mainnet,
        },
      },
      onFinish: (response) => {
        connectionStatus?.setAccounts(response.addresses as unknown as Account[]);
      },
      onCancel: () => {
        alert('Request canceled');
      },
    });
  } catch (err) {
    setWallet(null);
  }
}
```

I have reached out to their support as well, but please let me know any thoughts!

**Comment by victorkirov** [comment]
Yeah, their provider seems different. I don't know if they inject an ME specific provider. If they only inject one at window.BitcoinProvider, then you can check the value of `window.BitcoinProvider.isMagicEden`

**Comment by skyrover7** [comment]
![image](https://github.com/secretkeylabs/sats-connect/assets/42014195/d6527c65-b091-4a12-b1e5-d254bf46a020)

**Comment by victorkirov** [comment]
Looks like Xverse is the default provider in this case. If you want to force ME, go to the settings in Xverse and ensure that it's not the default, then go to the settings in ME and make it the default.

<img width="351" alt="image" src="https://github.com/secretkeylabs/sats-connect/assets/3322667/0c7cf250-33a8-46bb-a6db-57cd4847f6b1">
<img width="352" alt="image" src="https://github.com/secretkeylabs/sats-connect/assets/3322667/bda01db8-41f6-4215-9a2c-25d4ff815405">

**Comment by skyrover7** [comment]
Thanks @victorkirov, but I don't want to make ME the default. I just want to give the user a choice and I'm not sure the best way to achieve that.

**Comment by victorkirov** [comment]
It would just be for testing, but if the user has both Xverse and ME but Xverse is set to priority, then ME won't really be reachable. The only way would be for ME to inject into the default provider on window.BitcoinProvider and Xverse would be on window.XverseProviders.BitcoinProvider

**Comment by skyrover7** [comment]
@victorkirov i know you closed this, but is there any sample code available to achieve something like this?
