### ISSUE TITLE
How to update PSBTs

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#73]
I got this error, the inputs comes from a multisig script therefore it will need 2 signatures to be valid.

I am using sigHash: 131 // SIGHASH_SINGLE | ANYONECANPAY as shown in your tutorial

What am I doing wrong? I would like the first signer to approve the first input to be spent if there is a second output fixed

How can I do it?

![image](https://github.com/secretkeylabs/sats-connect/assets/42917076/74936bb9-89bb-4a31-9a73-fa6966426955)

**Comment by elRaulito** [comment]
Should I use taproot?

**Comment by victorkirov** [comment]
It looks like the PSBT has sighash single_anyone, but you aren't passing it in as an arg with the sign payload, so it's only allowing the default one (all).

See here how to notify that you want to use a non-default sighash:
https://github.com/secretkeylabs/sats-connect-example/blob/main/src/components/signTransaction.tsx#L73

**Comment by elRaulito** [comment]
Thanks @victorkirov 

I fixed but now it asks for a merkle tree for update the not signed utxo and it goes on error
![image](https://github.com/secretkeylabs/sats-connect/assets/42917076/83eb1e0b-324b-46b0-b5d7-44370ca755bb)

**Comment by victorkirov** [comment]
I'll need a lot more information about what you're trying to do and what you've set up and maybe some code snippets 😅

**Comment by elRaulito** [comment]
@victorkirov all is working now, my bad

The starting error was fixed as you said, will write it her for future people:


Adding this in the input added
`sighashType: Transaction.SIGHASH_SINGLE |Transaction.SIGHASH_ANYONECANPAY`

Adding this in the signature options

```
    inputsToSign: [
      {
        address: signer,
        signingIndexes: [index],
        sigHash: 131
      },
    ]
```

So on both sides

**Comment by victorkirov** [comment]
Awesome :) Gonna close this since it's all sorted 👍
