### ISSUE TITLE
Get taproot Address from publiKey

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#80]
I just connected my address and got this as pubKey for ordinals

`14803e27545dc1c220f5089a6ada4fa5c609dd50886d7abb47d30a866c981256`

I tried to get the Address shown on the wallet with this:

```
const toXOnly = pubKey => (pubKey.length === 32 ? pubKey : pubKey.slice(1, 33));
      let OrdinalPubKey =
        "035a99c71780945305f3a20356d55bcc7e8b681c3ef84c537cee5ee7e7da23163e";

      const BorrowerOrdinalPubKeyBuffer = Buffer.from(
        OrdinalPubKey,
        "hex"
      );

      // Create a P2WPKH (Pay to Witness Public Key Hash) script
      const p2trBorrower = payments.p2tr({
        pubkey: toXOnly(OrdinalPubKeyBuffer),
        network: network,
      });


      console.log(p2trBorrower)
```

Even without  `toXOnly` I keep getting different address than what I see in the wallet

tb1p53y6uvzx4uzw6m2hht7m0p8xlu8kqlmrulm5ng2kxsmpkfwndpjq64gl55

What's wrong?

**Comment by elRaulito** [comment]
So apparently from this publicKey

`a5d55ff9bbed4290b37f27d8a90b306c3f297b333a83d317c8c2792b93773013`

I get the following script

`5120f790a969c43abc0ecd34ccc1a2244c7feed623b70583930824b581fae6885ee7 `

that has `f790a969c43abc0ecd34ccc1a2244c7feed623b70583930824b581fae6885ee7` as hash inside the script and using it in payments.p2tr I get the right address

So the question is how to get 5120f790a969c43abc0ecd34ccc1a2244c7feed623b70583930824b581fae6885ee7 from a5d55ff9bbed4290b37f27d8a90b306c3f297b333a83d317c8c2792b93773013

Using `scure-btc-signer` as your example is not an issue and it works

**Comment by victorkirov** [comment]
Hi

Just to confirm, the pub key you are getting is via sats-connect? 

Could you please send through a list of what you're getting from sats-connect and I'll try parse them on my side to see what could be going wrong? 🙏  Something like:
paymentPubKey - 
paymentAddress -
ordinalsPubKey - 
ordinalsAddress - 

The ordinal pubkey you're getting ("035a99c71780945305f3a20356d55bcc7e8b681c3ef84c537cee5ee7e7da23163e") doesn't look like something we'd send back as an ordinal pub key as it has the Y value as a suffix, we already send the XOnly pubkey.

**Comment by elRaulito** [comment]
Will send you all the informations today

**Comment by victorkirov** [comment]
Someone else ran into this issue recently and I did a bit of a deep dive. I see you're using bitoinjs-lib...

The pub key we provide is the tap internal pub key. In your code where you use it, you're passing it in as the `pubkey` field, which equates to the tweaked pub key. You need to pass it in as the `internalPubkey` field and you'll get the right address.

**Comment by Roockeeeet** [comment]
#101
