### ISSUE TITLE
Where are defined all these things?

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#83]
Currently following this https://docs.xverse.app/sats-connect/guides/verify-message-signature

But there are no references about where to get

decodeBech32
secp256k1.recover
decodeSignature
and so on...

Let me know where can I import them from thanks

**Comment by jundihuang** [comment]
I also want to ask the same question

```
const varuint = require('varuint-bitcoin');
const secp256k1 = require('secp256k1');
const { hash160, hash256 } = require('bitcoinjs-lib').crypto;
const { SEGWIT_TYPES } = require('bitcoinjs-lib').address;
const bs58check = require('bs58check');
```

but i don't know how to get these functions 
`decodeSignature,  segwitRedeemHash, decodeBech32, bufferEquals`

**Comment by jundihuang** [comment]
@elRaulito I verified the signature using `bitcoinjs-message`

**Comment by victorkirov** [comment]
Yes, please use `bitcoinjs-message`. We'll update the docs accordingly 🙏

**Comment by elRaulito** [comment]
thanks @victorkirov
