### ISSUE TITLE
Is there any function from which I can listen the address change in xverse wallet?

### ISSUE THREAD

**Issue by mohitgarg05** [secretkeylabs/sats-connect#84]
Is there any function from which I can listen the address change in xverse wallet?

**Comment by victorkirov** [comment]
Hey @mohitgarg05 
This is not currently available but it's being worked on and will be released in an upcoming version.

**Comment by mohitgarg05** [comment]
Hey vector,
Thankx for your reply , i want to ask one more thing that is there any way
to impose gas fee on my btcTransfer?

Thank you
Mohit garh

**Comment by victorkirov** [comment]
Hey Mohit
Not at the moment. We're going to be adding that in as well but it won't be a hard setting, it will be an initial setting and the user can change the fees they want to use.

**Comment by teebszet** [comment]
duplicated with: https://github.com/secretkeylabs/sats-connect/issues/117 and https://github.com/secretkeylabs/sats-connect/issues/54
