### ISSUE TITLE
Error on Mainnet but not on Testnet

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#85]
![image](https://github.com/secretkeylabs/sats-connect/assets/42917076/fa60c60e-8f43-468d-8cba-cff8771b9c35)

Hey guys, so this is probably not related to sats-connect but since I am facing it with XVerse maybe you can help me:

Here a raw signed TX that is not able to submit, the error is:

`sendrawtransaction RPC error: {"code":-26,"message":"scriptpubkey"}`

This transaction on testnet doesnt' have any issues, is it related to OP_RETURN? does it have some restrictions on mainnet?

`0200000000010d2c17447f911aad6344769ad8ea55411ec1c794050c86f0d5af540ff1d126c89c01000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff100edf08da69cbfdad376f5deab1910cfab88c24cf76613a3df1ec2b7a77066105000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff100edf08da69cbfdad376f5deab1910cfab88c24cf76613a3df1ec2b7a77066104000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff100edf08da69cbfdad376f5deab1910cfab88c24cf76613a3df1ec2b7a77066100000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff5f409de07b795b3827e881cc7f903cc36b889e678de419a79851e6cb833e3b1e05000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff5f409de07b795b3827e881cc7f903cc36b889e678de419a79851e6cb833e3b1e04000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff5f409de07b795b3827e881cc7f903cc36b889e678de419a79851e6cb833e3b1e00000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff3582f7c38121f034af09379db6a3572fa4ca51f09a8bf5efe038bf0b5a1f4e3c07000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff3582f7c38121f034af09379db6a3572fa4ca51f09a8bf5efe038bf0b5a1f4e3c06000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff3582f7c38121f034af09379db6a3572fa4ca51f09a8bf5efe038bf0b5a1f4e3c05000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff3582f7c38121f034af09379db6a3572fa4ca51f09a8bf5efe038bf0b5a1f4e3c04000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff3582f7c38121f034af09379db6a3572fa4ca51f09a8bf5efe038bf0b5a1f4e3c03000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff3582f7c38121f034af09379db6a3572fa4ca51f09a8bf5efe038bf0b5a1f4e3c02000000171600140f2a9ea5758f3bc666c5a0fe23cad3b7e6c95610ffffffff04e803000000000000220020fd486ac739689ff8773628736fbc9ecfb77cf4edc982cbb952b13771a1d3742a6630b800000000002200207f4bce1d98b18e5592185a1e4a0664fec4584d68736271651200997f99113bf9f61847020000000017a91414c8f038188359736f6fbf99a5f9448d198083468700000000000000009d6a4c9a7b22636f6c6c223a22626974636f696e2d70757070657473222c2270416d6e74223a31323037313031342c226c416d6e74223a323839373034332c22617072223a3132352c22704b6579223a22303238663563656435363439646133373137353866323830363335663934613535386336386565653261633463376630373033343432356539376336303335326264222c2264617973223a377d024730440220718de1ab516958f22b5607795a3f4ea18aa18a93958638b3a8167203521e6309022027eef3e64506bdaf7218920f99ee3e4264bec5d56476e927cc722d902295300e0121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd02473044022015e926ebd9d1ad089750a0419e519bbe5e175659b789fccc749d99e91bd97575022009f66e7f1b2218121395e26984b3dd543a6ad59f82022372128bee40517e67920121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd024730440220363f3a52d0df8b932d243990d11ae9bd5ee88f4ee462ca3e3fe05a8d0e94bf5b022028d14468de98f4cdd682b09b006def497236dc452f66c9db0b174c5e5708705f0121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd0247304402200c8dc8243131f27f686257bffaf02083f347115f011ab142c50d8a764dba29b3022025f33170cde3028b637f2133d9c5f3dc20cd19efcf48882cb429be88f7165a050121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd0247304402205d2b5e650d80499efa0ba3f99e650e36250e742e7005e5aba9fccf0a0fa8e599022010b9cdd848f44e020f21786124ec819e7cd3945184737de1b1b8b544ded48e120121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd024730440220104e62f2b11c316e42b02ae87cccf47bfb32f28ae137282874bc32571528c34c0220542e2be186ca53fb1ceea8168eb8d1a319a6ff269c92c1a3001123795ce8a5ac0121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd02483045022100e9e6998f6a864b82c3976bb48894a564af3345ad5fa518246cfc42867db884f50220186dad88e858b92f1cb9c074d73b54a6d7979d7596ba7ad13c20ae2f3c5614dc0121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd0247304402205777caec1d7b213c12ca2bfaea8507a316c0d9d9329b164280c6b06a4565ac52022043bdca34157e731f554370d3d78fcd401ef509d7dfba0480ac08915fd44aad700121028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd0247304402200f8c4fb9ac3b57ac4386e958bd18df39f62eb48ba1e435aa095aabf834a2a09802204441acffafd3f0616dc98ea4f27c063f20a9b0f644e587a984db21`

**Comment by victorkirov** [comment]
I think this is most likely due to the limitation on the OP_RETURN byte size. In Mainnet it's limited to 80 bytes and yours is 156. Not sure why it's allowed in testnet 🤔

**Comment by elRaulito** [comment]
Thanks @victorkirov fixed changing way of compression to stay under 80 bytes

**Comment by victorkirov** [comment]
No probemo 🙂  Did it work? Can we close the ticket? 👀

**Comment by elRaulito** [comment]
Let's close it!
