### ISSUE TITLE
LOCKTIMEVERIFY issue on a transaction

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#88]
I am unable to submit this tx

I am spending an input that has 

```
      OP_IF
          ${script.number.encode(lockTime).toString("hex")}
          OP_CHECKLOCKTIMEVERIFY
          OP_DROP
      OP_ELSE
          ${alice}
          OP_CHECKSIGVERIFY
      OP_ENDIF
      ${bob}
      OP_CHECKSIG
```
As script

I keep getting: `non-mandatory-script-verify-flag (Locktime requirement not satisfied)` even if the locktime has past

`0200000000010294b306e9deba3ff7b83a3e451612823e10a861efc2e9cc40862e5525ed99c9c70000000000feffffff8ad216085a471cc0a13994d0857a0f54640b7a439ea72742f3af951103d6b401000000001716001483b3b0bf2864338e157d6afa74c9382e2f155ae6ffffffff032202000000000000225120f790a969c43abc0ecd34ccc1a2244c7feed623b70583930824b581fae6885ee7e80300000000000022002074f64a2e547a8e226ef0ed0e4a9856eb4a6566e2ddf52daa8822c1dcb0adc10b0000000000000000236a217b226964223a22363630323837656136366563653264613665356533376633227d0347304402206577f3749d0cc3fdb655494c138aa7166cf79de56fb02f9cba5e773eb7fbf0e402202b1f4c0c9b74eb20163dd1feebf17e0aba4f1af3a5358ea2af28ce9d23976de78101015063040a880266b1756721035a99c71780945305f3a20356d55bcc7e8b681c3ef84c537cee5ee7e7da23163ead68210307bf5747e92385958eafaa1da8d6649adc452b9f69fb3cf1fac6407a73a149d7ac02483045022100df61fd5bbeca42dc9f9835d472d732ddf563aebdec8382bce79761e7b256bcb502206bb38de746310de674e18d2d5131c6dadef3cc86d6e02d94b4bb9ede89811e9181210307bf5747e92385958eafaa1da8d6649adc452b9f69fb3cf1fac6407a73a149d700000000`

**Comment by victorkirov** [comment]
Looks like the locktime hasn't passed yet? I'll need a bit more info than this. Is that script tied to a taproot address? What's the rest of the script before the OP_IF? What locktime did you set? Too many unknowns 😋 

Also, you seem to be spending testnet funds, sending them to mainnet addresses 👀

**Comment by elRaulito** [comment]
It's not a taproot address while more a Native Segwit P2WSH, so using that script I generate the address with:

```
  const p2shmulti = payments.p2wsh({
      redeem: { output: scriptabove, network },
      network,
    });
```

Locktime I see inside encoded is: 0a880266 that should be 1711441930

to encode I use the function: `script.number.encode(1711441930).toString("hex")`

I am trying to spend now

I don't see any mainnet address in outputs, they are:

tb1p77g2j6wy827qanf5enq6yfzv0lhdvgahqkpexzpykkql4e5gtmns5cymxz

tb1qwnmy5tj5028zymhsa58y4xzkad9x2ehzmh6jm25gytqaev9dcy9ske45k6

(But I also noticed raw tx decoders see them as mainnet since they decode the script)

**Comment by victorkirov** [comment]
Ah, my bad. Didn't realise the decoders decoded to mainnet 😅 

Is it this txn? https://mempool.space/testnet/tx/c7c999ed25552e8640cce9c2ef61a8103e821216453e3ab8f73fbadee906b394

Looks like it has a locktime of 0 👀

**Comment by victorkirov** [comment]
This is a bit hard to figure this out from the hex. Do you have a code snippet of how you're compiling and finalising the txn?

**Comment by victorkirov** [comment]
Are you also using checklocktimeverify correctly? 🤔 
https://wiki.bitcoinsv.io/index.php/Opcodes_used_in_Bitcoin_Script#Used_NOP_opcode_identifiers

Are you setting a locktime for the txn?

**Comment by elRaulito** [comment]
I am trying to use this:

https://bitcoinjs-guide.bitcoin-studio.com/bitcoinjs-guide/v5/part-three-pay-to-script-hash/timelocks/cltv_p2wsh

This is exactly how I am finalizing the Tx

It's strange because with 0 as number it worked well in my past tests

**Comment by victorkirov** [comment]
I don't see a locktime in the decoded txn. Did you definitely run this line? `psbt.setLocktime(lockTime)`

It might just be the decoder though.

**Comment by elRaulito** [comment]
You are a genius

https://mempool.space/testnet/tx/964d9c6c5ee5eff610cb01436920781812c750236058a04705e9f853b5b6cd00

Please send a BTC address, or a twitter handle, you deserve to be celebrated

**Comment by victorkirov** [comment]
😂 Glad it worked! You can find me on Twitter at @vickirov 😄
