### ISSUE TITLE
Error signing PSBT Error: Input with not allowed sigHash=131. Allowed: 0

### ISSUE THREAD

**Issue by blieb** [secretkeylabs/sats-connect#9]
Hi,

I'm trying to sign a PSBT using the example code:

```
 onSignTransactionClick = async () => {
    const signPsbtOptions = {
      payload: {
        network: {
          type: "Mainnet",
        },
        message: "Sign Transaction",
        psbtBase64: "....",
        broadcast: false,
        inputsToSign: [
          {
            address: this.state.ordinalsAddress,
            signingIndexes: [0],
            sighash: 131
          },
        ], 
      },
      onFinish: (response) => {
        alert(response.psbtBase64);
      },
      onCancel: () => alert("Canceled"),
    };
    await signTransaction(signPsbtOptions);
  };
```

I need to sign the first and only input. The xverse dialog looks fine:
<img width="362" alt="Screenshot 2023-06-10 at 00 41 14" src="https://github.com/secretkeylabs/sats-connect/assets/540248/45d0027a-ffd3-4814-a54f-0a42395aa364">

but when I confirm I get the error: "Error signing PSBT Error: Input with not allowed sigHash=131. Allowed: 0"

what can be the reason of this error? this.state.ordinalsAddress is the correct address. I also tried to sign an other psbtBase64 from an other site (using  my wallet). So the psbt looks fine.

**Comment by yknl** [comment]
When you generated the PSBT did you set the sig hash?

**Comment by blieb** [comment]
> When you generated the PSBT did you set the sig hash?

Yes we set the sig hash in our nodejs backend as follows by the input:

`sighashType: bitcoin.Transaction.SIGHASH_SINGLE | bitcoin.Transaction.SIGHASH_ANYONECANPAY,`

**Comment by vuadenthuj1** [comment]
@blieb, Did you find an answer?

**Comment by blieb** [comment]
> @blieb, Did you find an answer?

No did not found solution yet. I also tried it with unsigned PSBT from magiceden. But that gives me the same error.

**Comment by timechainz** [comment]
Experiencing the exact same issue.

**Comment by yknl** [comment]
Looks like you set `sighash` instead of  `sigHash` 

It should look like:

```
        inputsToSign: [
          {
            address: this.state.ordinalsAddress,
            signingIndexes: [0],
            sigHash: 131
          },
        ], 
```

**Comment by blieb** [comment]
Oh strange, I thought I did copy it from docs, but looks good there. But uppercase H fixes it.
