### ISSUE TITLE
Can't Import sats-connect

### ISSUE THREAD

**Issue by beasthype** [secretkeylabs/sats-connect#96]
import Wallet from '../sats-connect';

I include this in my app.js file but on the client, it gets an error that it doesn't find it 

Please help

**Comment by victorkirov** [comment]
Hi

Could you provide more details please? Are you building a React app? Have you installed the dependency? What version of sats-connect have you installed?

You can see an example app here: https://github.com/secretkeylabs/sats-connect-example

Another note is that you are using a relative import. It should read `import ... from 'sats-connect'` and not `from '../sats-connect'`

**Comment by beasthype** [comment]
I'm building a website and using Node.js - I'm trying to add to my website a bitcoin wallet connection.

I followed the document and Imported this:
import Wallet from 'sats-connect';

but everytime I run it I get an error saying it cant find sats-connect. I installed this: npm install sats-connect@2.1.0

**Comment by beasthype** [comment]
// Add a click event listener to the 'connectWallet' button
document.getElementById('connectWallet').addEventListener('click', () => {
        const response = Wallet.request('getAccounts', {
        purposes: [AddressPurpose.Payment, AddressPurpose.Ordinals, AddressPurpose.Stacks],
        message: 'Cool app wants to know your addresses!',
      });
      console.log(Wallet.getAddress);

});

**Comment by victorkirov** [comment]
Are you using React or vanilla HTML + JS? If you're trying to import it in client side code, it won't work. It needs to be compiled into your built javascript artifacts. There is a way to build sats-connect so you can add it as a js file served from your server, but it's not possible by default.

**Comment by beasthype** [comment]
How co I do it? I use Html + js yes. I tried importing this from client side correct

**Comment by AmAzing129** [comment]
`import * as Wallet from 'sats-connect';`

**Comment by Roockeeeet** [comment]
npm run dev:
npm run build
const response = await Wallet.request('getAccounts', {
  purposes: [AddressPurpose.Payment, AddressPurpose.Ordinals, AddressPurpose.Stacks],
  message: 'Cool app wants to know your addresses!',
});
await Wallet.request('send Transfer', {...});

await Wallet.disconnect();

**Comment by victorkirov** [comment]
Following up on this. Did you manage to figure out the issue? If you were trying to import it on the client side JS, it wouldn't work as it needs to be baked into your built artifact for your site. There isn't a publicly available sats-connect version hosted somewhere reliable for this to work.
